title: Seth's Project Blog
description: > # this means to ignore newlines until "baseurl:"
  A place for write-ups about the projects that I'm working on.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.projects.sethpuckett.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Seth Puckett # add your name
author-img: seth.jpg # add your photo
about-author: Software developer. Weird guy.
social-twitter-seth: sethpuckett
social-instagram-seth: sethpuckett
social-github-seth: sethpuckett
social-linkedin-seth: sethpuckett
social-email-seth: puckett.seth@gmail.com

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
